apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: mohamedessam1911/weather-app-jenkins:latest
        ports:
        - containerPort: 5000
        env:
        - name: OPENWEATHER_API_KEY
          value: "d123db1878800d2c27119139eda255a7"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

